routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'DashboardController@index');

Auth::routes();

Route::get('login/{social}', 'Auth\LoginController@redirectToProvider');
Route::get('login/{social}/callback', 'Auth\LoginController@handleProviderCallback');

//Route::get('/home', 'HomeController@index')->name('home');

Route::get('/supplier/all', 'SupplierController@all');
Route::resource('supplier', 'SupplierController');

Route::get('/merchant/all', 'MerchantController@all');
Route::resource('merchant', 'MerchantController');

Route::get('/product/all', 'ProductController@all');
Route::get('/product/category', 'ProductController@category');
Route::post('/product/storecategory', 'ProductController@storeCategory')->name('product.storeCategory');
Route::delete('/product/categorydestroy/{id}', 'ProductController@categoryDestroy')->name('product.categoryDestroy');
Route::resource('product', 'ProductController');

Route::get('/purchase/all', 'PurchaseController@all');
Route::resource('purchase', 'PurchaseController');

Route::get('/sale/all', 'SaleController@all');
Route::resource('sale', 'SaleController');

Route::get('/balance/all', 'BalanceController@all');
Route::post('/balance/bymonth', 'BalanceController@bymonth');
Route::post('/balance/byyear', 'BalanceController@byyear');
Route::resource('balance', 'BalanceController');

Route::get('/staff/all', 'StaffController@all');
Route::resource('staff', 'StaffController');

Route::get('/asset/all', 'AssetController@all');
Route::resource('asset', 'AssetController');

Route::get('/store/all', 'StoreController@all');
Route::resource('store', 'StoreController');

Route::get('/damage/all', 'DamageController@all');
Route::resource('damage', 'DamageController');

Route::get('/user/all', 'UserController@all');
Route::put('/user/updateemail/{id}/', 'UserController@updateemail');
Route::put('/user/updatepassword/{id}/', 'UserController@updatepassword');
Route::resource('user', 'UserController');

Route::get('/transaction/addbank', 'TransactionController@addbank');
Route::post('/transaction/addbankstore', 'TransactionController@addbankstore');
Route::delete('/transaction/destroyaccount/{id}', 'TransactionController@destroyaccount')->name('transaction.destroyaccount');
Route::get('/transaction/all', 'TransactionController@all');
Route::resource('transaction', 'TransactionController');

Route::get('/invoice/{id}/pdf', 'InvoiceController@pdf');
Route::post('/invoice/sendinvoicetoEmail', 'InvoiceController@sendInvoiceToEmail');
Route::put('/invoice/invoicepayment/{id}', 'InvoiceController@invoicepayment');
Route::get('/invoice/all', 'InvoiceController@all');
Route::resource('invoice', 'InvoiceController');

Route::get('/payment/all', 'PaymentController@all');
Route::resource('payment', 'PaymentController');

Route::get('/smsemail/all', 'SmsemailController@all');
Route::post('/smsemail/smsbynumbers', 'SmsemailController@smsbynumbers');
Route::post('/smsemail/smsbygroup', 'SmsemailController@smsbygroup');
Route::post('/smsemail/emailbyemails', 'SmsemailController@emailbyemails');
Route::post('/smsemail/emailbygroups', 'SmsemailController@emailbygroups');
Route::resource('smsemail', 'SmsemailController');

Route::resource('settings', 'SettingsController');
Route::put('/settings/purchasecode/{code}', 'SettingsController@purchasecode');

Route::get('/users/purchases/', 'UsersController@purchases');
Route::get('/users/purchases/view/{id}', 'UsersController@purchasesshow');
Route::get('/users/supplies/', 'UsersController@supplies');
Route::get('/users/supplies/view/{id}', 'UsersController@suppliesshow');
Route::get('/users/invoices/', 'UsersController@invoices');
Route::get('/users/invoices/view/{id}', 'UsersController@invoiceshow');

Route::post('/payment/paypal/store/', 'PaypalController@store');
Route::get('/payment/paypal/status', 'PaypalController@getPaymentStatus');

Route::post('/payment/stripe/', 'StripeController@stripe');
//Route::post('/payment/stripe/', 'StripeController@stripe');


Route::post('/pos/paypal/payment/', 'PosController@payment');
Route::get('/pos/paypal/payment/status', 'PosController@paypalStatus');

// Route::post('/payment/stripe/', 'PosController@stripe');
//Route::post('/payment/stripe/', 'PosController@stripe');

Route::resource('pos', 'PosController');
Route::post('/pos/getProductsByCat/', 'PosController@getProductsByCat');
Route::post('/pos/addToCart/', 'PosController@addToCart');
Route::post('/pos/adjustToCart/', 'PosController@adjustToCart');
Route::post('/pos/updateBalance/', 'PosController@updateBalance');
Route::post('/pos/resetpos/', 'PosController@resetpos');
Route::post('/pos/payemnt/', 'PosController@payment');

/************* Verify Routes *************/
Route::get('/verify/', 'VerifyController@index');
Route::put('/verify/storePurchasecode/{id}', 'VerifyController@storePurchasecode');

app/Damage.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Damage extends Model
{
    //
}

app/Http/Controllers/DamageController.php
<?php

/*
| -----------------------------------------------------
| PRODUCT NAME: ABACUS - BUSINESS MANAGEMENT SYSTEM (ABMS)
| -----------------------------------------------------
| AUTHOR: ONEZEROART TEAM
| -----------------------------------------------------
| EMAIL: support@onezeroart.com
| -----------------------------------------------------
| COPYRIGHT: RESERVED BY ONEZEROART.COM
| -----------------------------------------------------
| AUTHOR PORTFOLIO: https://codecanyon.net/user/onezeroart/portfolio
| -----------------------------------------------------
| WEBSITE: http://onezeroart.com
| -----------------------------------------------------
*/

namespace App\Http\Controllers;
use Illuminate\Http\Request;
use App\Damage;
use App\Pcategories;
use App\Product;
use App\Merchant;
use App\Supplier;

class DamageController extends Controller {

        /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('checkverify');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        $data['categorieslist'] = Pcategories::all();
        $data['merchants'] = Merchant::all();
        $data['suppliers'] = Supplier::all();
        $data['products'] = Product::all();
        return view('damage.add')->with($data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        $data['categorieslist'] = Pcategories::all();
        $data['merchants'] = Merchant::all();
        $data['suppliers'] = Supplier::all();
        $data['products'] = Product::all();
        return view('damage.add')->with($data);
    }

    public function all() {
        $data['damages'] = Damage::all();
        $data['products'] = Product::all();
        return view('damage.all')->with($data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {
        $this->validate($request, [
            'product' => 'required',
            'date' => 'required',
            'category' => 'required',
            'merchant' => 'required',
            'supplier' => 'required',
            'quantity' => 'required',
            'total' => 'required',
        ]);

        $damage = new Damage;
        $damage->product = $request->product;
        $damage->description = $request->description;
        $damage->date = $request->date;
        $damage->category = $request->category;
        $damage->merchant = $request->merchant;
        $damage->supplier = $request->supplier;
        $damage->unit = $request->unit;
        $damage->quantity = $request->quantity;
        $damage->total = $request->total;
        $damage->save();
        return redirect('/damage/')->with('success', 'Successfully Added');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id) {
        $damage = Damage::findOrFail($id);
        return view('damage.show')->with('damage', $damage);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id) {
        $data['damage'] = Damage::findOrFail($id);
        $data['categorieslist'] = Pcategories::all();
        $data['merchants'] = Merchant::all();
        $data['suppliers'] = Supplier::all();
        $data['products'] = Product::all();
        return view('damage.edit')->with($data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id) {
        $this->validate($request, [
            'product' => 'required',
            'date' => 'required',
            'category' => 'required',
            'merchant' => 'required',
            'supplier' => 'required',
            'quantity' => 'required',
            'total' => 'required',
        ]);

        $damage = Damage::find($id);

        $damage->product = $request->product;
        $damage->description = $request->description;
        $damage->date = $request->date;
        $damage->category = $request->category;
        $damage->merchant = $request->merchant;
        $damage->supplier = $request->supplier;
        $damage->unit = $request->unit;
        $damage->quantity = $request->quantity;
        $damage->total = $request->total;
        $damage->save();
        return redirect('/damage/all')->with('success', 'Successfully Updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id) {
        Damage::find($id)->delete();
        return redirect('/damage/all')->with('success', 'Successfully Deleted');
    }

}

resources/views/damage/add.blade.php
@extends('layouts.app')

@section('content')

@php $arrayCatLists = array(' ' => 'انتخاب دسته بندی'); @endphp
@if(count($categorieslist) > 0 )                            
@foreach($categorieslist as $category)
@php                                 
$arrayCatLists[$category->category] = $category->category;
@endphp
@endforeach                        
@endif

@php $merchantslist = array(' ' => 'انتخاب بازرگان'); @endphp
@if(count($merchants) > 0 )                            
@foreach($merchants as $merchant)
@php 
$merchantslist[$merchant->id] = $merchant->fname;
@endphp
@endforeach                        
@endif

@php $supplierlist = array(' ' => 'انتخاب تامین کننده'); @endphp
@if(count($suppliers) > 0 )                            
@foreach($suppliers as $supplier)
@php 
$supplierlist[$supplier->id] = $supplier->fname;
@endphp
@endforeach                        
@endif

@php $productslist = array(' ' => 'انتخاب محصول'); @endphp
@if(count($products) > 0 )                            
@foreach($products as $product)
@php 
$productslist[$product->id] = $product->title;
@endphp
@endforeach                        
@endif   

<!-- Main content -->
<section class="content">
    <!-- Main row -->
    <div class="row">
        <div class="col-md-12">            
            <div class="box box-success">
                <div class="box-header with-border">
                    <h3 class="box-title">  محصول خسارت دیده جدید</h3>
                </div>
                <div class="box-body">

                    {!! Form::open(['action' => 'DamageController@store', 'files' => true, 'method' => 'POST']) !!}

                    
                    <div class="col-md-6">
                        <div class="form-group">
                            {{ Form::label('product', 'انتخاب محصول')}} <span class="text-red"> (*)</span>
                            <div class="input-group">                                                                      
                                {{ Form::select('product', $productslist, null, ['class' => 'form-control', 'required'] )}}
                            </div>
                        </div>
                    </div>
                    
                    <div class="col-md-6">
                        <div class="form-group">
                            {{ Form::label('date', 'تاریخ خسارت/ارجاع')}} <span class="text-red"> (*)</span>
                            <div class="input-group">                                                                  
                                {{ Form::text('date', '', ['class' => 'form-control datepicker', 'placeholder' => 'تاریخ خسارت/ارجاع', 'required'] )}}
                            </div>
                        </div>
                    </div>  
                    
                    <div class="col-md-12">
                        <div class="form-group">
                            {{ Form::label('description', 'توضیح')}}
                            <div class="input-group">                                                                      
                                {{ Form::textarea('description', '', ['class' => 'form-control', 'placeholder' => 'توضیح', 'rows' => 5] )}}
                            </div>
                        </div>
                    </div>
                    
                    <div class="col-md-4">
                        <div class="form-group">
                            {{ Form::label('category', 'انتخاب دسته بندی')}} <span class="text-red"> (*)</span>
                            <div class="input-group">                                                                      
                                {{ Form::select('category', $arrayCatLists, null, ['class' => 'form-control', 'required'] )}}
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            {{ Form::label('merchant', 'انتخاب بازرگان (مرجوع کننده)')}} <span class="text-red"> (*)</span>
                            <div class="input-group">                                                                      
                                {{ Form::select('merchant', $merchantslist, null, ['class' => 'form-control', 'required'] )}}
                            </div>
                        </div>
                    </div>                    
                    <div class="col-md-4">
                        <div class="form-group">
                            {{ Form::label('supplier', 'انتخاب تامین کننده')}} <span class="text-red"> (*)</span>
                            <div class="input-group">                                                                      
                                {{ Form::select('supplier', $supplierlist, null, ['class' => 'form-control', 'required'] )}}
                            </div>
                        </div>
                    </div>                    
                    <div class="col-md-4">
                        <div class="form-group">
                            {{ Form::label('unit', 'واحد شمارش')}} <span class="text-red"> (*)</span>
                            <div class="input-group">                                                                  
                                {{ Form::text('unit', '', ['class' => 'form-control', 'placeholder' => 'عدد/ست/دستگاه', 'required'] )}}
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            {{ Form::label('quantity', 'تعداد')}} <span class="text-red"> (*)</span>
                            <div class="input-group">                                                                  
                                {{ Form::text('quantity', '', ['class' => 'form-control quantity', 'placeholder' => 'تعداد', 'required'] )}}
                            </div>
                        </div>
                    </div>
                    
                    
                    <div class="col-md-4">
                        <div class="form-group">
                            {{ Form::label('total', 'کل مبلغ')}} <span class="text-red"> (*)</span>
                            <div class="input-group">                                                                  
                                {{ Form::number('total', '', ['class' => 'form-control total', 'placeholder' => 'کل مبلغ', 'required'] )}}
                            </div>
                        </div>
                    </div>
                    
                    <hr>

                    <div class="col-md-12">
                        <div class="form-group">                                
                            <div class="input-group">                                                                      
                                {{ Form::submit('ثبت', ['class' => 'btn btn-primary'] )}}
                            </div>
                        </div>
                    </div>   
                    
                    {!! Form::close() !!}

                </div>
            </div>
        </div>
    </div>
</section>

@endsection

resources/views/damage/all.blade.php
@extends('layouts.app')

@section('content')

<!-- Main content -->
<section class="content">
    <div class="row">

        <div class="col-md-12">
            <div class="box box-success">
                <div class="box-header with-border">
                    <h3 class="box-title">محصولات خسارت دیده</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <table class="table table-bordered table-hover dtProduct text-center">
                        <thead>
                            <tr>
                                <th style="width: 10px">#</th>
                                <th>تاریخ</th>
                                <th>محصول</th>
                                <th>دسته بندی</th>
                                <th>تامین کننده</th>
                                <th>بازرگان</th>
                                <th>تعداد</th>
                                <th>کل مبلغ</th>
                                <th>عملیات</th>
                            </tr>
                        </thead>
                        <tbody
                            @if(count($damages) > 0 )

                            @foreach($damages as $damage)

                                <tr>
                                    <td>{{ $loop->iteration }}</td>
                                    <td>{{ Carbon::parse($damage->damagedate)->format('j M Y') }}</td>
                                    <td><a title="Product Details" href="{{ url('product', $damage->product)}}">{{ Helper::getProductTitle( $damage->product ) }}</a></td>
                                    <td>{{ $damage->category }}</td>
                                    <td><a title="Supplier Details" href="{{ url('supplier', $damage->supplier)}}">{{ Helper::getNameByID($damage->supplier, 'suppliers') }}</a></td>
                                    <td><a title="Merchant Details" href="{{ url('merchant', $damage->merchant)}}">{{ Helper::getNameByID($damage->merchant, 'merchants') }}</a></td>
                                    <td>{{ number_format($damage->quantity, 2) }}</td>
                                    <td>{{ Helper::getCurrency(). " " . number_format($damage->total, 2) }}</td>
                                    <td>
                                        <span class="badge bg-blue"><a href="{{ url('damage', $damage->id)}}" title="نمایش"><i class="material-icons md-12">call_made</i></a></span>
                                        <span class="badge bg-yellow"><a href="{{ url('damage', $damage->id)}}/edit/" title="ویرایش"><i class="material-icons md-12">create</i></a></span>
                                        <form action="{{ route('damage.destroy', $damage->id) }}" method="POST">
                                            {{ method_field('DELETE') }}
                                            {{ csrf_field() }}
                                            <span><button class="badge bg-red delete" title="حذف"><i class="material-icons md-12">close</i></button></span>
                                        </form>
                                    </td>
                                </tr>

                            @endforeach
                            @endif

                        </tbody>
                    </table>
                </div>

            </div>
        </div>
    </div>
</section>

@endsection

resources/views/damage/edit.blade.php
@extends('layouts.app')

@section('content')

@php $arrayCatLists = array(' ' => 'انتخاب دسته بندی'); @endphp
@if(count($categorieslist) > 0 )                            
@foreach($categorieslist as $category)
@php                                 
$arrayCatLists[$category->category] = $category->category;
@endphp
@endforeach                        
@endif

@php $merchantslist = array(' ' => 'انتخاب بازرگان'); @endphp
@if(count($merchants) > 0 )                            
@foreach($merchants as $merchant)
@php 
$merchantslist[$merchant->id] = $merchant->fname;
@endphp
@endforeach                        
@endif

@php $supplierlist = array(' ' => 'انتخاب تامین کننده'); @endphp
@if(count($suppliers) > 0 )                            
@foreach($suppliers as $supplier)
@php 
$supplierlist[$supplier->id] = $supplier->fname;
@endphp
@endforeach                        
@endif

@php $productslist = array(' ' => 'انتخاب محصول'); @endphp
@if(count($products) > 0 )                            
@foreach($products as $product)
@php 
$productslist[$product->id] = $product->title;
@endphp
@endforeach                        
@endif   

<!-- Main content -->
<section class="content">
    <!-- Main row -->
    <div class="row">
        <div class="col-md-12">            
            <div class="box box-success">
                <div class="box-header with-border">
                    <h3 class="box-title">  ویرایش محصول خسارتی</h3>
                </div>
                <div class="box-body">

                    {!! Form::open(['action' => ['DamageController@update', $damage->id ], 'files' => true, 'method' => 'POST']) !!}
                    {{Form::hidden('_method', 'PUT')}}
                    
                    <div class="col-md-6">
                        <div class="form-group">
                            {{ Form::label('product', 'انتخاب محصول')}} <span class="text-red"> (*)</span>
                            <div class="input-group">                                                                      
                                {{ Form::select('product', $productslist, $damage->product, ['class' => 'form-control', 'required'] )}}
                            </div>
                        </div>
                    </div>
                    
                    <div class="col-md-6">
                        <div class="form-group">
                            {{ Form::label('date', 'تاریخ خسارت/ارجاع')}} <span class="text-red"> (*)</span>
                            <div class="input-group">                                                                  
                                {{ Form::text('date', $damage->date, ['class' => 'form-control datepicker', 'placeholder' => 'تاریخ خسارت/ارجاع', 'required'] )}}
                            </div>
                        </div>
                    </div>  
                    
                    <div class="col-md-12">
                        <div class="form-group">
                            {{ Form::label('description', 'توضیح')}}
                            <div class="input-group">                                                                      
                                {{ Form::textarea('description', $damage->description, ['class' => 'form-control', 'placeholder' => 'توضیح', 'rows' => 5] )}}
                            </div>
                        </div>
                    </div>
                    
                    <div class="col-md-4">
                        <div class="form-group">
                            {{ Form::label('category', 'انتخاب دسته بندی')}} <span class="text-red"> (*)</span>
                            <div class="input-group">                                                                      
                                {{ Form::select('category', $arrayCatLists, $damage->category, ['class' => 'form-control', 'required'] )}}
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            {{ Form::label('merchant', 'انتخاب بازرگان (مرجوع کننده)')}} <span class="text-red"> (*)</span>
                            <div class="input-group">                                                                      
                                {{ Form::select('merchant', $merchantslist, $damage->merchant, ['class' => 'form-control', 'required'] )}}
                            </div>
                        </div>
                    </div>                    
                    <div class="col-md-4">
                        <div class="form-group">
                            {{ Form::label('supplier', 'انتخاب تامین کننده')}} <span class="text-red"> (*)</span>
                            <div class="input-group">                                                                      
                                {{ Form::select('supplier', $supplierlist, $damage->supplier, ['class' => 'form-control', 'required'] )}}
                            </div>
                        </div>
                    </div>                    
                    <div class="col-md-4">
                        <div class="form-group">
                            {{ Form::label('unit', 'واحد شمارش')}}
                            <div class="input-group">                                                                  
                                {{ Form::text('unit', $damage->unit, ['class' => 'form-control', 'placeholder' => 'عدد/ست/دستگاه'] )}}
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            {{ Form::label('quantity', 'تعداد')}} <span class="text-red"> (*)</span>
                            <div class="input-group">                                                                  
                                {{ Form::text('quantity', $damage->quantity, ['class' => 'form-control quantity', 'placeholder' => 'تعداد', 'required'] )}}
                            </div>
                        </div>
                    </div>
                    
                    
                    <div class="col-md-4">
                        <div class="form-group">
                            {{ Form::label('total', 'کل مبلغ')}} <span class="text-red"> (*)</span>
                            <div class="input-group">                                                                  
                                {{ Form::number('total', $damage->total, ['class' => 'form-control total', 'placeholder' => 'کل مبلغ', 'required'] )}}
                            </div>
                        </div>
                    </div>
                    
                    <hr>

                    <div class="col-md-12">
                        <div class="form-group">                                
                            <div class="input-group">                                                                      
                                {{ Form::submit('ویرایش', ['class' => 'btn btn-primary'] )}}
                            </div>
                        </div>
                    </div>   
                    
                    {!! Form::close() !!}

                </div>
            </div>
        </div>
    </div>
</section>

@endsection

                    
                    