routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'DashboardController@index');

Auth::routes();

Route::get('login/{social}', 'Auth\LoginController@redirectToProvider');
Route::get('login/{social}/callback', 'Auth\LoginController@handleProviderCallback');

//Route::get('/home', 'HomeController@index')->name('home');

Route::get('/supplier/all', 'SupplierController@all');
Route::resource('supplier', 'SupplierController');

Route::get('/merchant/all', 'MerchantController@all');
Route::resource('merchant', 'MerchantController');

Route::get('/product/all', 'ProductController@all');
Route::get('/product/category', 'ProductController@category');
Route::post('/product/storecategory', 'ProductController@storeCategory')->name('product.storeCategory');
Route::delete('/product/categorydestroy/{id}', 'ProductController@categoryDestroy')->name('product.categoryDestroy');
Route::resource('product', 'ProductController');

Route::get('/purchase/all', 'PurchaseController@all');
Route::resource('purchase', 'PurchaseController');

Route::get('/sale/all', 'SaleController@all');
Route::resource('sale', 'SaleController');

Route::get('/balance/all', 'BalanceController@all');
Route::post('/balance/bymonth', 'BalanceController@bymonth');
Route::post('/balance/byyear', 'BalanceController@byyear');
Route::resource('balance', 'BalanceController');

Route::get('/staff/all', 'StaffController@all');
Route::resource('staff', 'StaffController');

Route::get('/asset/all', 'AssetController@all');
Route::resource('asset', 'AssetController');

Route::get('/store/all', 'StoreController@all');
Route::resource('store', 'StoreController');

Route::get('/damage/all', 'DamageController@all');
Route::resource('damage', 'DamageController');

Route::get('/user/all', 'UserController@all');
Route::put('/user/updateemail/{id}/', 'UserController@updateemail');
Route::put('/user/updatepassword/{id}/', 'UserController@updatepassword');
Route::resource('user', 'UserController');

Route::get('/transaction/addbank', 'TransactionController@addbank');
Route::post('/transaction/addbankstore', 'TransactionController@addbankstore');
Route::delete('/transaction/destroyaccount/{id}', 'TransactionController@destroyaccount')->name('transaction.destroyaccount');
Route::get('/transaction/all', 'TransactionController@all');
Route::resource('transaction', 'TransactionController');

Route::get('/invoice/{id}/pdf', 'InvoiceController@pdf');
Route::post('/invoice/sendinvoicetoEmail', 'InvoiceController@sendInvoiceToEmail');
Route::put('/invoice/invoicepayment/{id}', 'InvoiceController@invoicepayment');
Route::get('/invoice/all', 'InvoiceController@all');
Route::resource('invoice', 'InvoiceController');

Route::get('/payment/all', 'PaymentController@all');
Route::resource('payment', 'PaymentController');

Route::get('/smsemail/all', 'SmsemailController@all');
Route::post('/smsemail/smsbynumbers', 'SmsemailController@smsbynumbers');
Route::post('/smsemail/smsbygroup', 'SmsemailController@smsbygroup');
Route::post('/smsemail/emailbyemails', 'SmsemailController@emailbyemails');
Route::post('/smsemail/emailbygroups', 'SmsemailController@emailbygroups');
Route::resource('smsemail', 'SmsemailController');

Route::resource('settings', 'SettingsController');
Route::put('/settings/purchasecode/{code}', 'SettingsController@purchasecode');

Route::get('/users/purchases/', 'UsersController@purchases');
Route::get('/users/purchases/view/{id}', 'UsersController@purchasesshow');
Route::get('/users/supplies/', 'UsersController@supplies');
Route::get('/users/supplies/view/{id}', 'UsersController@suppliesshow');
Route::get('/users/invoices/', 'UsersController@invoices');
Route::get('/users/invoices/view/{id}', 'UsersController@invoiceshow');

Route::post('/payment/paypal/store/', 'PaypalController@store');
Route::get('/payment/paypal/status', 'PaypalController@getPaymentStatus');

Route::post('/payment/stripe/', 'StripeController@stripe');
//Route::post('/payment/stripe/', 'StripeController@stripe');


Route::post('/pos/paypal/payment/', 'PosController@payment');
Route::get('/pos/paypal/payment/status', 'PosController@paypalStatus');

// Route::post('/payment/stripe/', 'PosController@stripe');
//Route::post('/payment/stripe/', 'PosController@stripe');

Route::resource('pos', 'PosController');
Route::post('/pos/getProductsByCat/', 'PosController@getProductsByCat');
Route::post('/pos/addToCart/', 'PosController@addToCart');
Route::post('/pos/adjustToCart/', 'PosController@adjustToCart');
Route::post('/pos/updateBalance/', 'PosController@updateBalance');
Route::post('/pos/resetpos/', 'PosController@resetpos');
Route::post('/pos/payemnt/', 'PosController@payment');

/************* Verify Routes *************/
Route::get('/verify/', 'VerifyController@index');
Route::put('/verify/storePurchasecode/{id}', 'VerifyController@storePurchasecode');

app/Payments.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Payments extends Model
{
    //
}

app/Http/Controllers/PaymentController.php
<?php

/*
| -----------------------------------------------------
| PRODUCT NAME: ABACUS - BUSINESS MANAGEMENT SYSTEM (ABMS)
| -----------------------------------------------------
| AUTHOR: ONEZEROART TEAM
| -----------------------------------------------------
| EMAIL: support@onezeroart.com
| -----------------------------------------------------
| COPYRIGHT: RESERVED BY ONEZEROART.COM
| -----------------------------------------------------
| AUTHOR PORTFOLIO: https://codecanyon.net/user/onezeroart/portfolio
| -----------------------------------------------------
| WEBSITE: http://onezeroart.com
| -----------------------------------------------------
*/

namespace App\Http\Controllers;
use Illuminate\Http\Request;
use App\Payments;
use Carbon;

class PaymentController extends Controller {

        /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('checkverify');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        return view('payment.add');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        return view('payment.add');
    }

    public function all() {
        $data['payments'] = Payments::all();
        return view('payment.all')->with($data);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id) {
        Payments::find($id)->delete();
        return redirect('/payment/all')->with('success', 'Successfully Deleted');
    }


}

resources/views/payment/all.blade.php
@extends('layouts.app')
@section('content')

        <div class="col-md-12">
            <div class="box box-success">
                <div class="box-header with-border">
                    <h3 class="box-title">پرداخت ها</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <table class="table table-bordered table-hover dtPayment text-center">
                        <thead>
                            <tr>
                                <th style="width: 10px">#</th>
                                <th>شماره فاکتور #</th>
                                <th>نحوه پرداخت</th>
                                <th>پیگیری پرداخت</th>
                                <th>مبلغ</th>
                                <th>عملیات</th>
                            </tr>
                        </thead>
                        <tbody>

                            @if(count($payments) > 0 )

                            @foreach($payments as $payment)

                                <tr @if( $payment->type == "هزینه") style="background:#FFF9C4 !important" @endif>
                                    <td>{{ $loop->iteration }}</td>
                                    <td>{{ $payment->invoiceid }}</td>
                                    <td>{{ ucfirst($payment->paymentmethod) }}</td>
                                    <td>{{ $payment->paymentid }}</td>
                                    <td>{{ number_format($payment->amount, 2) }}</td>
                                    <td>
                                        <form action="{{ route('payment.destroy', $payment->id) }}" method="POST">
                                            {{ method_field('DELETE') }}
                                            {{ csrf_field() }}
                                            <span><button class="badge bg-red delete" title="حذف"><i class="material-icons md-12">close</i></button></span>
                                        </form>
                                    </td>
                                </tr>

                            @endforeach
                            @endif

                        </tbody>
                    </table>
                </div>

            </div>
        </div>
    </div>
</section>

@endsection