routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'DashboardController@index');

Auth::routes();

Route::get('login/{social}', 'Auth\LoginController@redirectToProvider');
Route::get('login/{social}/callback', 'Auth\LoginController@handleProviderCallback');

//Route::get('/home', 'HomeController@index')->name('home');

Route::get('/supplier/all', 'SupplierController@all');
Route::resource('supplier', 'SupplierController');

Route::get('/merchant/all', 'MerchantController@all');
Route::resource('merchant', 'MerchantController');

Route::get('/product/all', 'ProductController@all');
Route::get('/product/category', 'ProductController@category');
Route::post('/product/storecategory', 'ProductController@storeCategory')->name('product.storeCategory');
Route::delete('/product/categorydestroy/{id}', 'ProductController@categoryDestroy')->name('product.categoryDestroy');
Route::resource('product', 'ProductController');

Route::get('/purchase/all', 'PurchaseController@all');
Route::resource('purchase', 'PurchaseController');

Route::get('/sale/all', 'SaleController@all');
Route::resource('sale', 'SaleController');

Route::get('/balance/all', 'BalanceController@all');
Route::post('/balance/bymonth', 'BalanceController@bymonth');
Route::post('/balance/byyear', 'BalanceController@byyear');
Route::resource('balance', 'BalanceController');

Route::get('/staff/all', 'StaffController@all');
Route::resource('staff', 'StaffController');

Route::get('/asset/all', 'AssetController@all');
Route::resource('asset', 'AssetController');

Route::get('/store/all', 'StoreController@all');
Route::resource('store', 'StoreController');

Route::get('/damage/all', 'DamageController@all');
Route::resource('damage', 'DamageController');

Route::get('/user/all', 'UserController@all');
Route::put('/user/updateemail/{id}/', 'UserController@updateemail');
Route::put('/user/updatepassword/{id}/', 'UserController@updatepassword');
Route::resource('user', 'UserController');

Route::get('/transaction/addbank', 'TransactionController@addbank');
Route::post('/transaction/addbankstore', 'TransactionController@addbankstore');
Route::delete('/transaction/destroyaccount/{id}', 'TransactionController@destroyaccount')->name('transaction.destroyaccount');
Route::get('/transaction/all', 'TransactionController@all');
Route::resource('transaction', 'TransactionController');

Route::get('/invoice/{id}/pdf', 'InvoiceController@pdf');
Route::post('/invoice/sendinvoicetoEmail', 'InvoiceController@sendInvoiceToEmail');
Route::put('/invoice/invoicepayment/{id}', 'InvoiceController@invoicepayment');
Route::get('/invoice/all', 'InvoiceController@all');
Route::resource('invoice', 'InvoiceController');

Route::get('/payment/all', 'PaymentController@all');
Route::resource('payment', 'PaymentController');

Route::get('/smsemail/all', 'SmsemailController@all');
Route::post('/smsemail/smsbynumbers', 'SmsemailController@smsbynumbers');
Route::post('/smsemail/smsbygroup', 'SmsemailController@smsbygroup');
Route::post('/smsemail/emailbyemails', 'SmsemailController@emailbyemails');
Route::post('/smsemail/emailbygroups', 'SmsemailController@emailbygroups');
Route::resource('smsemail', 'SmsemailController');

Route::resource('settings', 'SettingsController');
Route::put('/settings/purchasecode/{code}', 'SettingsController@purchasecode');

Route::get('/users/purchases/', 'UsersController@purchases');
Route::get('/users/purchases/view/{id}', 'UsersController@purchasesshow');
Route::get('/users/supplies/', 'UsersController@supplies');
Route::get('/users/supplies/view/{id}', 'UsersController@suppliesshow');
Route::get('/users/invoices/', 'UsersController@invoices');
Route::get('/users/invoices/view/{id}', 'UsersController@invoiceshow');

Route::post('/payment/paypal/store/', 'PaypalController@store');
Route::get('/payment/paypal/status', 'PaypalController@getPaymentStatus');

Route::post('/payment/stripe/', 'StripeController@stripe');
//Route::post('/payment/stripe/', 'StripeController@stripe');


Route::post('/pos/paypal/payment/', 'PosController@payment');
Route::get('/pos/paypal/payment/status', 'PosController@paypalStatus');

// Route::post('/payment/stripe/', 'PosController@stripe');
//Route::post('/payment/stripe/', 'PosController@stripe');

Route::resource('pos', 'PosController');
Route::post('/pos/getProductsByCat/', 'PosController@getProductsByCat');
Route::post('/pos/addToCart/', 'PosController@addToCart');
Route::post('/pos/adjustToCart/', 'PosController@adjustToCart');
Route::post('/pos/updateBalance/', 'PosController@updateBalance');
Route::post('/pos/resetpos/', 'PosController@resetpos');
Route::post('/pos/payemnt/', 'PosController@payment');

/************* Verify Routes *************/
Route::get('/verify/', 'VerifyController@index');
Route::put('/verify/storePurchasecode/{id}', 'VerifyController@storePurchasecode');

app/Supplier.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Supplier extends Model
{
    //
}

app/Http/Controllers/SupplierController.php
<?php

/*
| -----------------------------------------------------
| PRODUCT NAME: ABACUS - BUSINESS MANAGEMENT SYSTEM (ABMS)
| -----------------------------------------------------
| AUTHOR: ONEZEROART TEAM
| -----------------------------------------------------
| EMAIL: support@onezeroart.com
| -----------------------------------------------------
| COPYRIGHT: RESERVED BY ONEZEROART.COM
| -----------------------------------------------------
| AUTHOR PORTFOLIO: https://codecanyon.net/user/onezeroart/portfolio
| -----------------------------------------------------
| WEBSITE: http://onezeroart.com
| -----------------------------------------------------
*/

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Supplier;
use App\Purchase;
use Image;

class SupplierController extends Controller {

        /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('checkverify');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        return view('supplier.add');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        return view('supplier.add');
    }

    public function all() {
        $suppliers = Supplier::all();
        $data['suppliers'] = $suppliers;
        return view('supplier.all')->with($data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {
        $this->validate($request, [
            'supplierid' => 'required',
            'fname' => 'required',
            'phone' => 'required',
            'photo' => 'image|mimes:jpeg,png,jpg,gif,svg',
        ]);

        $supplier = new Supplier;

        $image = $request->file('photo');
        if ($request->file('photo')) {
            $supplier->photo = time() . '.' . $image->getClientOriginalExtension();
            $imagePath = public_path('/images/supplier');
            $img = Image::make($image->getRealPath());
            $img->resize(250, 250, function ($constraint) {
                $constraint->aspectRatio();
            })->save($imagePath . '/' . $supplier->photo);
        }

        $supplier->supplierid = $request->input('supplierid');
        $supplier->fname = $request->input('fname');
        $supplier->lname = $request->input('lname');
        $supplier->phone = $request->input('phone');
        $supplier->fax = $request->input('fax');
        $supplier->email = $request->input('email');
        $supplier->company = $request->input('company');
        $supplier->cheque = $request->input('cheque');
        $supplier->bank = $request->input('bank');
        $supplier->account = $request->input('account');
        $supplier->paypal = $request->input('paypal');
        $supplier->other = $request->input('other');
        $supplier->address = $request->input('address');
        $supplier->about = $request->input('about');
        $supplier->facebook = $request->input('facebook');
        $supplier->twitter = $request->input('twitter');
        $supplier->youtube = $request->input('youtube');
        $supplier->map = $request->input('map');

        $supplier->save();
        return redirect('/supplier')->with('success', 'Successfully Added');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id) {
        $data['purchases'] = Purchase::where('supplier', $id)->get();
        $data['supplier'] = Supplier::where('id', $id)->firstOrFail();
        return view('supplier.show')->with($data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id) {
        $supplier = Supplier::where('id', $id)->firstOrFail();
        return view('supplier.edit')->with('supplier', $supplier);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id) {
        $this->validate($request, [
            'supplierid' => 'required',
            'fname' => 'required',
            'phone' => 'required',
            'photo' => 'image|mimes:jpeg,png,jpg,gif,svg',
        ]);

        $supplier = Supplier::find($id);

        $image = $request->file('photo');
        if ($request->file('photo')) {
            $supplier->photo = time() . '.' . $image->getClientOriginalExtension();
            $imagePath = public_path('/images/supplier');
            $img = Image::make($image->getRealPath());
            $img->resize(250, 250, function ($constraint) {
                $constraint->aspectRatio();
            })->save($imagePath . '/' . $supplier->photo);
        }

        $supplier->supplierid = $request->input('supplierid');
        $supplier->fname = $request->input('fname');
        $supplier->lname = $request->input('lname');
        $supplier->phone = $request->input('phone');
        $supplier->fax = $request->input('fax');
        $supplier->email = $request->input('email');
        $supplier->company = $request->input('company');
        $supplier->cheque = $request->input('cheque');
        $supplier->bank = $request->input('bank');
        $supplier->account = $request->input('account');
        $supplier->paypal = $request->input('paypal');
        $supplier->other = $request->input('other');
        $supplier->address = $request->input('address');
        $supplier->about = $request->input('about');
        $supplier->facebook = $request->input('facebook');
        $supplier->twitter = $request->input('twitter');
        $supplier->youtube = $request->input('youtube');
        $supplier->map = $request->input('map');
        $supplier->save();

        return redirect('/supplier/' . $id)->with('success', 'Successfully Updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id) {
        Supplier::find($id)->delete();
        return redirect('/supplier/all')->with('success', 'Successfully Deleted');
    }

}

resources/views/supplier/all.blade.php
@extends('layouts.app')

@section('content')

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-success">
                <div class="box-header with-border">
                    <h3 class="box-title">تامین کنندگان</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <table class="table table-bordered table-hover dtSupplier text-center">
                        <thead>
                            <tr>
                                <th style="width: 10px">#</th>
                                <th>ID</th>
                                <th>تامین کننده</th>
                                <th>تلفن</th>
                                <th>ایمیل</th>
                                <th>نام کارخانه</th>
                                <th>عملیات</th>
                            </tr>
                        </thead>
                        <tbody
                            @if(count($suppliers) > 0 )

                            @foreach($suppliers as $supplier)

                                <tr>
                                    <td>{{ $loop->iteration }}</td>
                                    <td>{{ $supplier->supplierid }}</td>
                                    <td>{{ $supplier->fname }} {{ $supplier->lname }}</td>
                                    <td>{{ $supplier->phone }}</td>
                                    <td>{{ $supplier->email }}</td>
                                    <td>{{ $supplier->company }}</td>
                                    <td>
                                        <span class="badge bg-blue"><a href="{{ url('supplier', $supplier->id) }}" title="نمایش"><i class="material-icons md-12">call_made</i></a></span>
                                        <span class="badge bg-yellow"><a href="{{ url('supplier', $supplier->id) }}/edit" title="ویرایش"><i class="material-icons md-12">create</i></a></span>

                                        <form action="{{ route('supplier.destroy', $supplier->id) }}" method="POST">
                                            {{ method_field('DELETE') }}
                                            {{ csrf_field() }}
                                            <span><button class="badge bg-red delete" title="حذف"><i class="material-icons md-12">close</i></button></span>
                                        </form>
                                    </td>
                                </tr>

                            @endforeach
                            @endif

                        </tbody>
                    </table>
                </div>

            </div>
        </div>
    </div>
</section>

@endsection

resources/views/supplier/show.blade.php
@extends('layouts.app')

@section('content')

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-widget widget-user-2 box-success">

                <div class="widget-user-header bg-primary">
                    <!-- /.widget-user-image -->
                    <h3 class="widget-user-username">{{ $supplier->fname }} {{ $supplier->lname }}</h3>
                    <h5 class="widget-user-desc">Supplier | {{ $supplier->company }}</h5>
                </div>

                <!-- /.box-header -->
                <div class="box-body">
                    <div class="col-md-12">
                        <!-- Custom Tabs -->
                        <div class="nav-tabs-custom" dir="rtl">
                            <ul class="nav nav-tabs">
                                <li class="active"><a href="#tab_1" data-toggle="tab" aria-expanded="false">اصلی</a></li>
                                <li class=""><a href="#tab_2" data-toggle="tab" aria-expanded="false">درباره</a></li>
                                <li class=""><a href="#tab_3" data-toggle="tab" aria-expanded="false">آدرس</a></li>
                                <li class=""><a href="#tab_4" data-toggle="tab" aria-expanded="false">تراکنشها</a></li>
                            </ul>
                            <div class="tab-content">
                                <div class="tab-pane active" id="tab_1">
                                    <div class="profile widget-user-image">

                                        <?php if($supplier->photo){ ?>
                                            <img src="{{ URL::asset('images/supplier/' . $supplier->photo)}}" alt="User Avatar">
                                        <?php } else{ ?>
                                            <img src="{{ URL::asset('images/default.png')}}" alt="User Avatar">
                                        <?php } ?>

                                    </div>
                                    <table class="table table-bordered">
                                        <tbody>
                                            <tr>
                                                <td>آیدی/سریال</td>
                                                <td>{{ $supplier->supplierid }}</td>
                                            </tr>
                                            <tr>
                                                <td>نام</td>
                                                <td>{{ $supplier->fname }} {{ $supplier->lname }}</td>
                                            </tr>
                                            <tr>
                                                <td>تلفن</td>
                                                <td>{{ $supplier->phone }}</td>
                                            </tr>
                                            <tr>
                                                <td>فکس</td>
                                                <td>{{ $supplier->fax }}</td>
                                            </tr>
                                            <tr>
                                                <td>ایمیل</td>
                                                <td>{{ $supplier->email }}</td>
                                            </tr>
                                            <tr>
                                                <td>نام کارخانه</td>
                                                <td>{{ $supplier->company }}</td>
                                            </tr>
                                            {{-- <tr>
                                                <td>Cheque Issue Name</td>
                                                <td>{{ $supplier->cheque }}</td>
                                            </tr> --}}
                                            <tr>
                                                <td>نام بانک</td>
                                                <td>{{ $supplier->bank }}</td>
                                            </tr>
                                            <tr>
                                                <td>شماره حساب بانکی</td>
                                                <td>{{ $supplier->account }}</td>
                                            </tr>
                                            <tr>
                                                <td>Paypal اکانت</td>
                                                <td>{{ $supplier->paypal }}</td>
                                            </tr>
                                            <tr>
                                                <td>روش دیگر پرداخت</td>
                                                <td>{{ $supplier->other }}</td>
                                            </tr>
                                            <tr>
                                                <td>Social Media Links</td>
                                                <td>
                                                    <a class="btn btn-social-icon btn-facebook" href="{{ $supplier->facebook }}"><i class="fa fa-facebook"></i></a>
                                                    <a class="btn btn-social-icon btn-twitter" href="{{ $supplier->twitter }}"><i class="fa fa-twitter"></i></a>
                                                    <a class="btn btn-social-icon btn-google" href="{{ $supplier->youtube }}"><i class="fa fa-youtube"></i></a>
                                                </td>
                                            </tr>
                                        </tbody></table>
                                </div>
                                <!-- /.tab-pane -->
                                <div class="tab-pane" id="tab_2">
                                    {!! $supplier->about !!}
                                </div>
                                <div class="tab-pane" id="tab_3">
                                    {!! $supplier->address !!}
                                </div>
                                <!-- /.tab-pane -->
                                <div class="tab-pane" id="tab_4">
                                    <table class="table table-bordered table-hover dtProduct text-center">
                        <thead>
                            <tr>
                                <th style="width: 10px">#</th>
                                <th>تاریخ</th>
                                <th>محصول</th>
                                <th>تعداد</th>
                                <th>قیمت</th>
                                <th>کمیسیون</th>
                                <th>قیمت کل</th>
                                <th>عملیات</th>
                            </tr>
                        </thead>
                        <tbody
                            @if(count($purchases) > 0 )

                            @foreach($purchases as $purchase)

                                <tr>
                                    <td>{{ $loop->iteration }}</td>
                                    <td>{{ Carbon::parse($purchase->purchasedate)->format('j M Y') }}</td>
                                    <td>{{ $purchase->title }}</td>
                                    <td>{{ number_format($purchase->quantity) }}</td>
                                    <td>{{ number_format($purchase->price) }}</td>
                                    <td>{{ number_format($purchase->commission) }}</td>
                                    <td>{{ number_format($purchase->total) }}</td>
                                    <td>
                                        <span class="badge bg-blue"><a href="{{ url('purchase', $purchase->id) }}" title="نمایش"><i class="material-icons md-12">call_made</i></a></span>
                                        <span class="badge bg-yellow"><a href="{{ url('purchase', $purchase->id) }}/edit/" title="ویرایش"><i class="material-icons md-12">create</i></a></span>
                                        <form action="{{ route('purchase.destroy', $purchase->id) }}" method="POST">
                                            {{ method_field('DELETE') }}
                                            {{ csrf_field() }}
                                            <span><button class="badge bg-red delete" title="حذف"><i class="material-icons md-12">close</i></button></span>
                                        </form>
                                    </td>
                                </tr>

                            @endforeach
                            @endif

                        </tbody>
                    </table>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>

            </div>
        </div>
    </div>
</section>

@endsection