routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'DashboardController@index');

Auth::routes();

Route::get('login/{social}', 'Auth\LoginController@redirectToProvider');
Route::get('login/{social}/callback', 'Auth\LoginController@handleProviderCallback');

//Route::get('/home', 'HomeController@index')->name('home');

Route::get('/supplier/all', 'SupplierController@all');
Route::resource('supplier', 'SupplierController');

Route::get('/merchant/all', 'MerchantController@all');
Route::resource('merchant', 'MerchantController');

Route::get('/product/all', 'ProductController@all');
Route::get('/product/category', 'ProductController@category');
Route::post('/product/storecategory', 'ProductController@storeCategory')->name('product.storeCategory');
Route::delete('/product/categorydestroy/{id}', 'ProductController@categoryDestroy')->name('product.categoryDestroy');
Route::resource('product', 'ProductController');

Route::get('/purchase/all', 'PurchaseController@all');
Route::resource('purchase', 'PurchaseController');

Route::get('/sale/all', 'SaleController@all');
Route::resource('sale', 'SaleController');

Route::get('/balance/all', 'BalanceController@all');
Route::post('/balance/bymonth', 'BalanceController@bymonth');
Route::post('/balance/byyear', 'BalanceController@byyear');
Route::resource('balance', 'BalanceController');

Route::get('/staff/all', 'StaffController@all');
Route::resource('staff', 'StaffController');

Route::get('/asset/all', 'AssetController@all');
Route::resource('asset', 'AssetController');

Route::get('/store/all', 'StoreController@all');
Route::resource('store', 'StoreController');

Route::get('/damage/all', 'DamageController@all');
Route::resource('damage', 'DamageController');

Route::get('/user/all', 'UserController@all');
Route::put('/user/updateemail/{id}/', 'UserController@updateemail');
Route::put('/user/updatepassword/{id}/', 'UserController@updatepassword');
Route::resource('user', 'UserController');

Route::get('/transaction/addbank', 'TransactionController@addbank');
Route::post('/transaction/addbankstore', 'TransactionController@addbankstore');
Route::delete('/transaction/destroyaccount/{id}', 'TransactionController@destroyaccount')->name('transaction.destroyaccount');
Route::get('/transaction/all', 'TransactionController@all');
Route::resource('transaction', 'TransactionController');

Route::get('/invoice/{id}/pdf', 'InvoiceController@pdf');
Route::post('/invoice/sendinvoicetoEmail', 'InvoiceController@sendInvoiceToEmail');
Route::put('/invoice/invoicepayment/{id}', 'InvoiceController@invoicepayment');
Route::get('/invoice/all', 'InvoiceController@all');
Route::resource('invoice', 'InvoiceController');

Route::get('/payment/all', 'PaymentController@all');
Route::resource('payment', 'PaymentController');

Route::get('/smsemail/all', 'SmsemailController@all');
Route::post('/smsemail/smsbynumbers', 'SmsemailController@smsbynumbers');
Route::post('/smsemail/smsbygroup', 'SmsemailController@smsbygroup');
Route::post('/smsemail/emailbyemails', 'SmsemailController@emailbyemails');
Route::post('/smsemail/emailbygroups', 'SmsemailController@emailbygroups');
Route::resource('smsemail', 'SmsemailController');

Route::resource('settings', 'SettingsController');
Route::put('/settings/purchasecode/{code}', 'SettingsController@purchasecode');

Route::get('/users/purchases/', 'UsersController@purchases');
Route::get('/users/purchases/view/{id}', 'UsersController@purchasesshow');
Route::get('/users/supplies/', 'UsersController@supplies');
Route::get('/users/supplies/view/{id}', 'UsersController@suppliesshow');
Route::get('/users/invoices/', 'UsersController@invoices');
Route::get('/users/invoices/view/{id}', 'UsersController@invoiceshow');

Route::post('/payment/paypal/store/', 'PaypalController@store');
Route::get('/payment/paypal/status', 'PaypalController@getPaymentStatus');

Route::post('/payment/stripe/', 'StripeController@stripe');
//Route::post('/payment/stripe/', 'StripeController@stripe');


Route::post('/pos/paypal/payment/', 'PosController@payment');
Route::get('/pos/paypal/payment/status', 'PosController@paypalStatus');

// Route::post('/payment/stripe/', 'PosController@stripe');
//Route::post('/payment/stripe/', 'PosController@stripe');

Route::resource('pos', 'PosController');
Route::post('/pos/getProductsByCat/', 'PosController@getProductsByCat');
Route::post('/pos/addToCart/', 'PosController@addToCart');
Route::post('/pos/adjustToCart/', 'PosController@adjustToCart');
Route::post('/pos/updateBalance/', 'PosController@updateBalance');
Route::post('/pos/resetpos/', 'PosController@resetpos');
Route::post('/pos/payemnt/', 'PosController@payment');

/************* Verify Routes *************/
Route::get('/verify/', 'VerifyController@index');
Route::put('/verify/storePurchasecode/{id}', 'VerifyController@storePurchasecode');

app/Merchant.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Merchant extends Model
{
    //
}

app/Http/Controllers/MerchantController.php
<?php

/*
| -----------------------------------------------------
| PRODUCT NAME: ABACUS - BUSINESS MANAGEMENT SYSTEM (ABMS)
| -----------------------------------------------------
| AUTHOR: ONEZEROART TEAM
| -----------------------------------------------------
| EMAIL: support@onezeroart.com
| -----------------------------------------------------
| COPYRIGHT: RESERVED BY ONEZEROART.COM
| -----------------------------------------------------
| AUTHOR PORTFOLIO: https://codecanyon.net/user/onezeroart/portfolio
| -----------------------------------------------------
| WEBSITE: http://onezeroart.com
| -----------------------------------------------------
*/

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Merchant;
use App\Sale;
use Image;

class MerchantController extends Controller {

        /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('checkverify');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        return view('merchant.add');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        return view('merchant.add');
    }

    public function all() {
        $merchants = Merchant::all();
        $data['merchants'] = $merchants;
        return view('merchant.all')->with($data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {

        $this->validate($request, [
            'merchantid' => 'required',
            'fname' => 'required',
            'phone' => 'required',
            'photo' => 'image|mimes:jpeg,png,jpg,gif,svg',
        ]);

        $merchant = new Merchant();
        $image = $request->file('photo');
        if ($request->file('photo')) {
            $merchant->photo = time() . '.' . $image->getClientOriginalExtension();
            $imagePath = public_path('/images/merchant');
            $img = Image::make($image->getRealPath());
            $img->resize(250, 250, function ($constraint) {
                $constraint->aspectRatio();
            })->save($imagePath . '/' . $merchant->photo);
        }

        $merchant->merchantid = $request->input('merchantid');
        $merchant->fname = $request->input('fname');
        $merchant->lname = $request->input('lname');
        $merchant->phone = $request->input('phone');
        $merchant->fax = $request->input('fax');
        $merchant->email = $request->input('email');
        $merchant->company = $request->input('company');
        $merchant->tradelicense = $request->input('tradelicense');
        $merchant->otherlicense = $request->input('otherlicense');
        $merchant->address = $request->input('address');
        $merchant->about = $request->input('about');
        $merchant->facebook = $request->input('facebook');
        $merchant->twitter = $request->input('twitter');
        $merchant->youtube = $request->input('youtube');
        $merchant->map = $request->input('map');
        $merchant->Save();
        return redirect('/merchant')->with('success', 'Merchant Inserted');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id) {
        $data['sales'] = Sale::orderBy('id','DESC')->where('merchant', $id)->get();
        $data['merchant'] = Merchant::findOrFail($id);
        return view('merchant.show')->with($data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id) {
        $data = Merchant::findOrFail($id);
        return view('merchant.edit')->with('merchant', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id) {

        $this->validate($request, [
            'merchantid' => 'required',
            'fname' => 'required',
            'phone' => 'required',
            'photo' => 'image|mimes:jpeg,png,jpg,gif,svg',
        ]);

        $merchant = Merchant::find($id);
        $image = $request->file('photo');
        if ($request->file('photo')) {
            $merchant->photo = time() . '.' . $image->getClientOriginalExtension();
            $imagePath = public_path('/images/merchant');
            $img = Image::make($image->getRealPath());
            $img->resize(250, 250, function ($constraint) {
                $constraint->aspectRatio();
            })->save($imagePath . '/' . $merchant->photo);
        }

        $merchant->merchantid = $request->input('merchantid');
        $merchant->fname = $request->input('fname');
        $merchant->lname = $request->input('lname');
        $merchant->phone = $request->input('phone');
        $merchant->fax = $request->input('fax');
        $merchant->email = $request->input('email');
        $merchant->company = $request->input('company');
        $merchant->tradelicense = $request->input('tradelicense');
        $merchant->otherlicense = $request->input('otherlicense');
        $merchant->address = $request->input('address');
        $merchant->about = $request->input('about');
        $merchant->facebook = $request->input('facebook');
        $merchant->twitter = $request->input('twitter');
        $merchant->youtube = $request->input('youtube');
        $merchant->map = $request->input('map');
        $merchant->save();
        return redirect('/merchant/' . $id)->with('success', 'Successfully Updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id) {
        Merchant::find($id)->delete();
        return redirect('/merchant/all')->with('success', 'Successfully Deleted');
    }

}

resources/views/merchant/all.blade.php
@extends('layouts.app')

@section('content')

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-success">
                <div class="box-header with-border">
                    <h3 class="box-title">همه بازرگانان/واردکنندگان</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <table class="table table-bordered table-hover dtMerchant text-center">
                        <thead>
                            <tr>
                                <th style="width: 10px">#</th>
                                <th>آی دی</th>
                                <th>نام</th>
                                <th>تلفن</th>
                                <th>ایمیل</th>
                                <th>کارخانه</th>
                                <th>عملیات</th>
                            </tr>
                        </thead>
                        <tbody
                            @if(count($merchants) > 0 )

                            @foreach($merchants as $merchant)

                                <tr>
                                    <td>{{ $loop->iteration }}</td>
                                    <td>{{ $merchant->merchantid }}</td>
                                    <td>{{ $merchant->fname }} {{ $merchant->lname }}</td>
                                    <td>{{ $merchant->phone }}</td>
                                    <td>{{ $merchant->email }}</td>
                                    <td>{{ $merchant->company }}</td>
                                    <td>
                                        <span class="badge bg-blue"><a href="{{ url('merchant', $merchant->id) }}" title="نمایش"><i class="material-icons md-12">call_made</i></a></span>
                                        <span class="badge bg-yellow"><a href="{{ url('merchant', $merchant->id) }}/edit" title="ویرایش"><i class="material-icons md-12">create</i></a></span>
                                        <form action="{{ route('merchant.destroy', $merchant->id) }}" method="POST">
                                            {{ method_field('DELETE') }}
                                            {{ csrf_field() }}
                                            <span><button class="badge bg-red delete" title="حذف"><i class="material-icons md-12">close</i></button></span>
                                        </form>
                                    </td>
                                </tr>

                            @endforeach
                            @endif

                        </tbody>
                    </table>
                </div>

            </div>
        </div>
    </div>
</section>

@endsection

resources/views/merchant/show.blade.php
@extends('layouts.app')

@section('content')

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-widget widget-user-2 box-success">

                <div class="widget-user-header bg-primary">
                    <h3 class="widget-user-username">{{ $merchant->fname }} {{ $merchant->lname }}</h3>
                    <h5 class="widget-user-desc">بازرگان | {{ $merchant->company }}</h5>
                </div>


                <!-- /.box-header -->
                <div class="box-body">
                    <div class="col-md-12">
                        <!-- Custom Tabs -->
                        <div class="nav-tabs-custom">
                            <ul class="nav nav-tabs">
                                <li class="active"><a href="#tab_1" data-toggle="tab" aria-expanded="false">اصلی</a></li>
                                <li class=""><a href="#tab_2" data-toggle="tab" aria-expanded="false">درباره</a></li>
                                <li class=""><a href="#tab_3" data-toggle="tab" aria-expanded="false">آدرس</a></li>
                                <li class=""><a href="#tab_4" data-toggle="tab" aria-expanded="false">تراکنش ها</a></li>
                            </ul>
                            <div class="tab-content">
                                <div class="tab-pane active" id="tab_1">
                                    <div class="profile widget-user-image">

                                        <?php if($merchant->photo){ ?>
                                            <img src="{{ URL::asset('images/merchant/' . $merchant->photo)}}" alt="User Avatar">
                                        <?php } else{ ?>
                                            <img src="{{ URL::asset('images/default.png')}}" alt="User Avatar">
                                        <?php } ?>

                                    </div>
                                    <!-- /.widget-user-image -->
                                    <table class="table table-bordered">
                                        <tbody>
                                            <tr>
                                                <td>آی دی/سریال</td>
                                                <td>{{ $merchant->merchantid }}</td>
                                            </tr>
                                            <tr>
                                                <td>نام</td>
                                                <td>{{ $merchant->fname }} {{ $merchant->lname }}</td>
                                            </tr>
                                            <tr>
                                                <td>تلفن</td>
                                                <td>{{ $merchant->phone }}</td>
                                            </tr>
                                            <tr>
                                                <td>فکس</td>
                                                <td>{{ $merchant->fax }}</td>
                                            </tr>
                                            <tr>
                                                <td>ایمیل</td>
                                                <td>{{ $merchant->email }}</td>
                                            </tr>
                                            <tr>
                                                <td>نام کارخانه</td>
                                                <td>{{ $merchant->company }}</td>
                                            </tr>
                                            <tr>
                                                <td>مجوز تجارت</td>
                                                <td>{{ $merchant->tradelicense }}</td>
                                            </tr>
                                            <tr>
                                                <td>لایسنس های دیگر</td>
                                                <td>{{ $merchant->otherlicense }}</td>
                                            </tr>
                                            <tr>
                                                <td>شبکه های اجتماعی</td>
                                                <td>
                                                    <a class="btn btn-social-icon btn-facebook" href="{{ $merchant->facebook }}"><i class="fa fa-facebook"></i></a>
                                                    <a class="btn btn-social-icon btn-twitter" href="{{ $merchant->twitter }}"><i class="fa fa-twitter"></i></a>
                                                    <a class="btn btn-social-icon btn-google" href="{{ $merchant->youtube }}"><i class="fa fa-youtube"></i></a>
                                                </td>
                                            </tr>

                                        </tbody></table>
                                </div>
                                <!-- /.tab-pane -->
                                <div class="tab-pane" id="tab_2">
                                    {!! $merchant->about !!}
                                </div>
                                <div class="tab-pane" id="tab_3">
                                    {!! $merchant->address !!}
                                </div>
                                <!-- /.tab-pane -->
                                <div class="tab-pane" id="tab_4">
                                    <table class="table table-bordered table-hover dtProduct text-center">
                                        <thead>
                                            <tr>
                                                <th style="width: 10px">#</th>
                                                <th>تاریخ</th>
                                                <th>محصول</th>
                                                <th>بازرگان</th>
                                                <th>تعداد</th>
                                                <th>کل مبلغ</th>
                                                <th>پرداختی</th>
                                                <th>ناشی از</th>
                                                <th style="width: 20%">عملیات</th>
                                            </tr>
                                        </thead>
                                        <tbody
                                            @if(count($sales) > 0 )

                                            @foreach($sales as $sale)

                                            @php
                                            $totalSubtotal = array();
                                            $productIDs = $sale->product; //Product IDs
                                            $productQtys = $sale->quantity; //Product Quantity
                                            $productPrices = $sale->price; //Product price

                                            //Product IDs
                                            $productArr = explode(",", $productIDs);
                                            foreach ($productArr as $prokey => $provalue){
                                                if ($provalue == "") {
                                                    unset($productArr[$prokey]);
                                                }
                                            }

                                            //Product Quantity
                                            $productQtyArr = explode(",", $productQtys);
                                            foreach ($productQtyArr as $proQtykey => $proQtyvalue){
                                                if ($proQtyvalue == "") {
                                                    unset($productQtyArr[$proQtykey]);
                                                }
                                            }

                                            //Product Price
                                            $productPriceArr = explode(",", $productPrices);
                                            foreach ($productPriceArr as $proPrikey => $proPrivalue){
                                                if ($proPrivalue == "") {
                                                    unset($productPriceArr[$proPrikey]);
                                                }
                                            }

                                            foreach ($productArr as $productkey => $product){
                                                $totalSubtotal[] = $productPriceArr[$productkey]  * $productQtyArr[$productkey];
                                            }

                                            $totalSubtotal = array_sum($totalSubtotal);


                                            @endphp

                                                <tr>
                                                    <td>{{ $loop->iteration }}</td>
                                                    <td>{{ Carbon::parse($sale->saledate)->format('j M Y') }}</td>
                                                    <td>

                                                            <?php for($sq=0; count($productArr) > $sq; $sq++){
                                                                if(!empty($productArr[$sq])){ ?>
                                                                    <a title="جزئیات محصول" href="{{ url('product', $productArr[$sq]) }}">{{ Helper::getProductTitle( $productArr[$sq] ) }}</a><br>
                                                                <?php }
                                                                if($sq === 1){ ?>
                                                                    <a title="محصولات بیشتر" href="{{ url('sale', $sale->id) }}">...</a><br>
                                                                <?php break;
                                                                }
                                                            } ?>

                                                    </td>
                                                    <td><a title="Merchant Details" href="{{ url('merchant', $sale->merchant) }}">{{ Helper::getNameByID($sale->merchant, 'merchants') }}</a></td>
                                                    <td>{{ number_format(array_sum($productQtyArr), 2) }}</td>
                                                    <td><strong>{{ number_format($totalSubtotal - $sale->commission, 2)  }}</strong></td>

                                                    <?php if( Helper::invoiceBySale($sale->id) != false ){ ?>
                                                        <td><strong> <?php if( Helper::invoiceBySale($sale->id)){ echo number_format(Helper::invoiceBySale($sale->id)->paidamount); } ?></strong></td>
                                                    <?php if( Helper::invoiceBySale($sale->id)->paidamount < ($totalSubtotal - $sale->commission) ){ ?>
                                                        <td><strong> {{ number_format( Helper::invoiceBySale($sale->id)->paidamount - ($totalSubtotal - $sale->commission)) }}</strong></td>
                                                    <?php }else{ ?>
                                                        <td>N/A</td>
                                                    <?php } }else{ ?>
                                                            <td>N/A</td>
                                                            <td>N/A</td>
                                                    <?php } ?>
                                                    
                                                    <td>
                                                        <span class="badge bg-blue"><a href="{{ url('purchase', $sale->id) }}" title="نمایش"><i class="material-icons md-12">call_made</i></a></span>
                                                        <span class="badge bg-yellow"><a href="{{ url('purchase', $sale->id) }}/edit/" title="ویرایش"><i class="material-icons md-12">create</i></a></span>
                                                        <form action="{{ route('purchase.destroy', $sale->id) }}" method="POST">
                                                            {{ method_field('DELETE') }}
                                                            {{ csrf_field() }}
                                                            <span><button class="badge bg-red delete" title="حذف"><i class="material-icons md-12">close</i></button></span>
                                                        </form>
                                                    </td>
                                                </tr>

                                            @endforeach
                                            @endif

                                        </tbody>
                                    </table>
                                </div>
                                <!-- /.tab-pane -->
                            </div>
                            <!-- /.tab-content -->
                        </div>
                        <!-- nav-tabs-custom -->
                    </div>

                </div>

            </div>
        </div>
    </div>
</section>

@endsection